export enum Permission {
  SEND_MESSAGES = 'SEND_MESSAGES',
  REACT_TO_MESSAGES = 'REACT_TO_MESSAGES',
  PIN_MESSAGES = 'PIN_MESSAGES',
  UPLOAD_FILES = 'UPLOAD_FILES',
  JOIN_VOICE_CHANNELS = 'JOIN_VOICE_CHANNELS',
  SHARE_SCREEN = 'SHARE_SCREEN',
  ENABLE_WEBCAM = 'ENABLE_WEBCAM',
  // ADMIN PERMISSIONS
  MANAGE_CHANNELS = 'MANAGE_CHANNELS',
  MANAGE_CHANNEL_PERMISSIONS = 'MANAGE_CHANNEL_PERMISSIONS',
  MANAGE_CATEGORIES = 'MANAGE_CATEGORIES',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_EMOJIS = 'MANAGE_EMOJIS',
  MANAGE_SETTINGS = 'MANAGE_SETTINGS',
  MANAGE_USERS = 'MANAGE_USERS',
  MOVE_MEMBERS = 'MOVE_MEMBERS',
  MANAGE_MESSAGES = 'MANAGE_MESSAGES',
  MANAGE_STORAGE = 'MANAGE_STORAGE',
  MANAGE_INVITES = 'MANAGE_INVITES',
  MANAGE_UPDATES = 'MANAGE_UPDATES',
  MANAGE_PLUGINS = 'MANAGE_PLUGINS',
  MANAGE_PLUGIN_PERMISSIONS = 'MANAGE_PLUGIN_PERMISSIONS',
  USE_PLUGINS = 'USE_PLUGINS',
  VIEW_USER_SENSITIVE_DATA = 'VIEW_USER_SENSITIVE_DATA'
}

export const DEFAULT_ROLE_PERMISSIONS = [
  Permission.JOIN_VOICE_CHANNELS,
  Permission.SEND_MESSAGES,
  Permission.UPLOAD_FILES,
  Permission.SHARE_SCREEN,
  Permission.ENABLE_WEBCAM
];

export enum ChannelPermission {
  VIEW_CHANNEL = 'VIEW_CHANNEL',
  SEND_MESSAGES = 'SEND_MESSAGES',
  JOIN = 'JOIN',
  SPEAK = 'SPEAK',
  SHARE_SCREEN = 'SHARE_SCREEN',
  WEBCAM = 'WEBCAM'
}
